spring.application.name=spring-security
spring.security.user.name=nathan
spring.security.user.password=1234

server.servlet.session.cookie.same-site=strict

spring.datasource.url=jdbc:postgresql://localhost:5432/telusko
spring.datasource.username=Nathan_N
spring.datasource.password=1111
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true